### ISSUE TITLE
Condense forum guidance posts into one post

### ISSUE THREAD

**Issue by LexaMichaelides** [hyphacoop/cosmos-organizing#105]
Currently there are different guidance posts:
- https://forum.cosmos.network/t/getting-started-on-the-forum/5726 
- https://forum.cosmos.network/t/best-practices-for-proposal-makers/6245
- https://forum.cosmos.network/t/forum-moderation-policy/6192
- https://forum.cosmos.network/t/suggested-naming-conventions-for-proposals/5725/2
- https://forum.cosmos.network/t/governance-process-overview/5724/2

They need to be interlinked and/or condensed to make it easier to share a single link to help people get started.

**Comment by LexaMichaelides** [comment]
My vision for this:
- 'About the Category' posts should serve as the main source of information about a particular category. This is most relevant for the proposals, I think. 
- The 'Start Here' post should be the single source of all information (with links to other posts as though it is also the table of contents)

**Comment by LexaMichaelides** [comment]
Condensed many posts into this: https://forum.cosmos.network/t/start-here-participating-in-the-forum/5993

I see value in keeping the mod policy and naming conventions separate as they may require independent links or edits.

**Comment by LexaMichaelides** [comment]
Minor updates to Proposal Types section of this master post. Should also put the templates for each proposal text into that proposal type's 'About the Category' post.

**Comment by LexaMichaelides** [comment]
Made adjustments to Proposal Types section of master post and added templates for each proposal typle.
Waiting on @uditvira 's thoughts on how to describe 'Client Update' proposal in this section:

```
Signalling Proposal: Signal an intent through text proposals. The only kind of proposal that does not directly cause any change.
Community Spend Proposal: Spend tokens from the community pool.
Parameter Change Proposal: Change on-chain parameters.
Software Upgrade Proposal: Propose a software upgrade at a specified halt height.
**Client Update Proposal: Upgrades a particular client.**

```

**Comment by uditvira** [comment]
you can replace with `Client Update Proposal: Update an expired IBC client with a substitute client.`

for more background, you can read this ADR https://github.com/cosmos/ibc-go/blob/main/docs/architecture/adr-026-ibc-client-recovery-mechanisms.md
