### ISSUE TITLE
Diskspace full

### ISSUE THREAD

**Issue by ASoTNetworks** [hyphacoop/cosmos-organizing#106]
We saw 2 validators was alerting about running out of disk space and the others are also running out.
Before the v7 upgrade cosmovisor created a data-backup directory while upgrading which contains all the data of the chain before the upgrade in case of failure.

We removed that directory to free up space.

We will test out pruning on one of the nodes to see how it preform and update the node operator's handbook.

**Comment by uditvira** [comment]
Pruning plan:

- Try on sentry-02 node first
- Set min-retain-blocks > unbonding time
- Set pruning to everything

Calculation for min-retain-blocks:
- un bonding time = 2 days (you can find here https://testnet.cosmos.bigdipper.live/params)
- rough block time = 5.5 seconds/block
- (2 day * 24 hr/day * 60 min/hr * 60 s/hr)/5.5s/block = 31418.18 blocks
- let's round that to 32000 blocks for min-retain blocks

**Comment by dasanchez** [comment]
Apr 27 update:
Mar 31-Apr 7 window
`sentry-01`: 77.6GB -> 89.0GB: 11.4GB increase
`sentry-02`: 75.8GB -> 89.3GB: 13.5GB increase 
Increase in disk usage is 2.1GB lower in `sentry-01`.

Apr 20-Apr 27 window
`sentry-01`: 73.4GB -> 79.8GB: 6.4GB increase
`sentry-02`: 74.8GB -> 79.5GB: 4.7GB increase 
`sentry-02` has pruning set to everything
Increase in disk usage is 1.7GB lower.

**Comment by dasanchez** [comment]
IG uses this pruner, we could try it out:
https://github.com/binaryholdings/cosmprund

**Comment by dasanchez** [comment]
Will experiment with `cosmprund`
