### ISSUE TITLE
Deprecate Vega testnet

### ISSUE THREAD

**Issue by uditvira** [hyphacoop/cosmos-organizing#107]
Communications

- [x] Make software upgrade proposal https://vega-explorer.hypha.coop/proposals/67
- [x] Communicate it out (asked Noam) https://hackmd.io/mLMwzvQbS2KDaKa1erWHgA?view
- [x] Remove from Faucet by giving error when someone asks for Vega testnet tokens: "Vega testnet is no longer active from April 14, 2022. Please use Theta instead" @dasanchez

Machines: @ASoTNetworks 
- [x] Shutdown nodes
- [x] Backup data
- [x] Tear down machines

**Comment by dasanchez** [comment]
I created an issue in the `cosmos-discord-faucet` repo:
https://github.com/hyphacoop/cosmos-discord-faucet/issues/8

**Comment by uditvira** [comment]
Also adding:

Remove from monitoring and reporting @ASoTNetworks 
- [ ] Monitoring Matrix channel
- [ ] Panic telegram chat
- [ ] Grafana boards

**Comment by dasanchez** [comment]
@uditvira I asked Noam to update the stickied message in the Discord channel, it will be updated soon.
