### ISSUE TITLE
Write and send update to multisig members

### ISSUE THREAD

**Issue by LexaMichaelides** [hyphacoop/cosmos-organizing#119]

**Comment by maisutton** [comment]
Created a Telegram group with Daniel, Lauren, Lexa, Udit, and myself and sent them our update.

**Comment by LexaMichaelides** [comment]
Mai Sutton, [Apr 25, 2022 at 3:26:18 PM]:
Hey Lauren, Daniel,

We wanted to give you an update on the work we've done on activating the Discourse forum, which we'd scoped for the governance proposal that passed. We're also sending you the rough breakdown of our budget for the 1000 ATOM our multisig received. Let us know if you have any questions! »

Forum
Revamped the forum and made category architecture changes to make it easier to post and browse threads.
Adjusted post names on all past proposal posts to make them more findable. 
Added lots of content to the forum to guide people in how to engage, what to post, templates to help people draft proposals. 
Continued moderation and community engagement with posts including helping BlocksUnited refine Prop 66 (which passed!)

Twitter / Promotion
Using @ CosmosGov to tweet updates about proposals and link back to the forum.
Upcoming: Moving summaries as proposals exist on the forum.

Internal / Structural
Published brief moderation policy - still want to continue refining how we interact with people on the forum.
Created budget buckets to think about how we want to allocate money (see below)

Upcoming Work
Working on governance digest content to summarize major happenings in Hub governance in the past month.
Planning how other collaborators can get involved in this work.

Budget
1000 ATOM = $29150.00 USD (as of 24 Mar 2022)
Proposed time budget in proposal: “250-300 hours over six months”
>> 500 ATOM to go to community for scoped work

Anticipated payouts at halfway point (3 months into the pilot - end of June) and at end of pilot (end of Sept) both to Hypha contributors and other collaborators.
 
1000 ATOM / 300 hrs = 3.3 ATOM
3.3 ATOM * $29.15 = $97.16 / hour

300 HOURS / 26 weeks (6 months) = ~11.5 hours/week
Moderation – 3 hrs/week = 26% 
Facilitation – 3 hrs/week = 26% 
Engagement – 2 hrs/week = 17.3
Guidance – 2.5 hrs/week = 21.7% 
Administration – 1 hr/week = 9%
