### ISSUE TITLE
Ship 1st monthly digest

### ISSUE THREAD

**Issue by uditvira** [hyphacoop/cosmos-organizing#128]
@LexaMichaelides has written this out here. We should ship this on May 9th. https://docs.google.com/document/d/1h5FArNPIG9cTlQZR1qzX-i2OVyXwGCt3bSacRvzflqA/edit#heading=h.6y8os8u8ubr8

- needs a post on forum 
- mini tweet thread from CosmosGov twitter

**Comment by LexaMichaelides** [comment]
Tweet thread: https://docs.google.com/document/d/1xWfjx_szUY0aCQWg49JZPQaxHKgTMnYUqJuqaMIpt9w/edit#heading=h.xl0q5n70h6i1
