### ISSUE TITLE
Scope out tasks on fun+accessible gaia repo :sparkles:

### ISSUE THREAD

**Issue by dcwalk** [hyphacoop/cosmos-organizing#13]
Update:  Part of the OKR for gaia team this qtr is to make the repo more fun+accessible

We've focused on process for governance but now with merge of repos are looking at how to have gov docs, etc. align with this :)

Est.: 2 hrs

**Comment by dcwalk** [comment]
just dropping this docs / testnet issues in gaia @uditvira if you think we could contribute at all:

```
https://github.com/cosmos/gaia/issues/760
```

**Comment by uditvira** [comment]
what could this include?
* making the docs more visually appealing

**Comment by dcwalk** [comment]
b9labs https://drive.google.com/file/d/10FL6geH6lCIa9UJE9Zt2sN-xoEGYaH3h/view?usp=sharing

**Comment by uditvira** [comment]
- [ ] ping jessica and chat about this task

**Comment by dcwalk** [comment]
Going to chat with noam + jessica next week RE: docs and see if there is something to itemize from there.

**Comment by dcwalk** [comment]
Had the chat, next step is I will call the marketing / gaia repo call with j, b9, n? for the duration of the docs refresh !
