### ISSUE TITLE
Create shell script that reads a config file to modify a genesis.json file

### ISSUE THREAD

**Issue by ASoTNetworks** [hyphacoop/cosmos-organizing#14]
- chain config
  - old chain id and what to modify it to
- validators (can be many)
  - old address and new address
- modify delegation power
- modify governance parameters

**Comment by uditvira** [comment]
* Elon is working on it
* Udit to do a co-work with Elon tomorrow

Scope
- Input files
  - config file
  - genesis.json
- output file
  - modified_genesis.json

**Comment by uditvira** [comment]
estimate hours: 3 hours

**Comment by uditvira** [comment]
Shahan had this script to run multiple validators and have over 66% voting power https://github.com/cosmos/gaia/pull/861/files#diff-2acff95d35429bc3d640536b7ac208c84276715e232d9d4731cbde9537046cae
