### ISSUE TITLE
Develop OKRs for q1 2022

### ISSUE THREAD

**Issue by uditvira** [hyphacoop/cosmos-organizing#15]

**Comment by uditvira** [comment]
- vuepress website
- testnet playbook
- role definition (think through coinbase SLA)

**Comment by dcwalk** [comment]
#roadmap-okr-reporting

**Comment by uditvira** [comment]
blocked on SLA

**Comment by uditvira** [comment]
* udit to write these out for next week to share with Mai + Lexa on the governance side

**Comment by uditvira** [comment]
This is what I'm thinking:

General themes to focus on 2022

Roll out of the testnet program: Hypha will manage the set up around all upcoming Cosmos Hub testnets (Theta, Lambda, Rho) in 2022. We will work with the Gaia team to coordinate releases, support validators joining the testnet, onboard new testnet users, and ensure the testnet runs smoothly.

Improve Cosmos Hub governance workflows through hands-on experimentation with processes (e.g., forming on-chain committees, developing a metadata standard for off-chain governance deliberation, developing on-ramps for participation through education, etc.). The goal here is to increase engagement, reduce apathy, and improve the quality of deliberation related to the Hub.

Objectives and Results for Q1 2022
Objectives
* Increase Theta testnet validator participation 
* Ensure testnet matches mainnet conditions more closely
* Have hands-on experience with on-chain proposals
* Bring focus and attention to the governance forum

Results
* Have at least 25 validators participating for the upgrade process
* Have mainnet and testnet upgrade time difference to be no more than 15%
* Take at least 1 proposal to an on-chain vote and meet quorum 
* Bring the daily engaged user number on the forum up to 6 (currently 2.5)

**Comment by uditvira** [comment]
maria says she likes the OKR's

**Comment by uditvira** [comment]
@maisutton @LexaMichaelides to look at these before closing out
