### ISSUE TITLE
Post-merge tasks in Gaia for governance docs

### ISSUE THREAD

**Issue by dcwalk** [hyphacoop/cosmos-organizing#24]
After #10 lands (soooon), there are some immediate archiving tasks in the governance repo (documented in other issue)

And in the gaia repo proposing something like the following:

refinements:
- ~~issue template for docs ●○○  (auto-label: governance docs)~~ not valuable in hindsight, backlog grooming seems sufficient
- [x] PR template for governance proposals ●○○  (auto-label: governance docs, form for draft proposal checklist?) `https://github.com/cosmos/gaia/pull/1050`  
- [x] integrate current params update script ~integrate into docs build process~ ●●○  `https://github.com/cosmos/gaia/pull/1051` 
- [x] identify relevant issues in gaia that can be addressed as governance add tag ●○○

~new 'features': ~ (rescoped)
~- [ ] overhaul page structure for governance section ●●●~
   ~ - things that fit better as tutorials? or resources?~
~- [ ] Add initial JSON schema ●●○ ~
~- [ ] Amend in something abt governance to contributing? ●○○~
   ~ - https://github.com/cosmos/gaia/blob/main/CONTRIBUTING.md~

**Comment by uditvira** [comment]
rescoping to remove new features
