### ISSUE TITLE
Address Infra access issues (was: Ben orient with Cosmos and Hypha)

### ISSUE THREAD

**Issue by uditvira** [hyphacoop/cosmos-organizing#25]
@eenblam
- try to set up a local testnet on hypha infrastructure by following the local testnet readme on the vega-test repository
- noting gaps in our documentation on hypha side and cosmos side

**Comment by eenblam** [comment]
Hoping to have capacity here middle of next week.

**Comment by uditvira** [comment]
@eenblam were you able to set up a local testnet? can I close this issue?

**Comment by eenblam** [comment]
@uditvira Sorry, no, details below. CC @asotnetworks

Roadblock:
* Visited https://github.com/hyphacoop/handbook/pull/137
* Just see notes that info is missing. See links that seem helpful, but I don't have access to that repo:
    * https://github.com/hyphacoop/organizing-private/issues/141
    * https://github.com/hyphacoop/organizing-private/issues/141#issuecomment-882102078
 
 Videos are mentioned, but don't know where the videos are.
 
## Accessing Proxmox
 Viewed https://github.com/hyphacoop/handbook/blob/b050f49d96cdf01a1c3ba262f0118b5dc91d1036/guides.md#virtual-machines
 * Tried SSH, but I'm not sure I actually have the key?
     * Should I be using a key on the jump server instead?
     * I still don't have the password for the root user on Kvm1.
 * Tried VPN. I can connect to VPN, but I don't have access to the shared password entry in Passbolt
 
 ## Accessing jump server
Completed PR.

However, I can't resolve ansible1.hypha.stg when on VPN. I'm assuming that the "Connection to [production|staging] Ansible1..." instructions are meant to be used from the jump server... but there aren't instructions on how to connect to the jump server, or even what its hostname is.

EDIT: I see [in this comment](https://github.com/hyphacoop/handbook/pull/137/files#r705800370) instructions for instead connecting to ansible1.hypha.prod, but again, I'm not able to resolve that hostname. How are y'all configuring your DNS?

**Comment by eenblam** [comment]
Also, this isn't blocking me, but I did run into it while getting set up. Just something to be aware for future onboarding.

## User VPN instructions
Your VPN config options require OpenVPN3, which isn't actually available in Ubuntu 20.04 and earlier. For users setting up their VPN, it might be helpful to clarify:
* You need OpenVPN v3. It's possible to install this as `openvpn3` alongside your system install of `openvpn`. [Details here](https://community.openvpn.net/openvpn/wiki/OpenVPN3Linux).
* OpenVPN 3 uses a very different syntax at the command line. I found the below functions helpful to add to my `.bashrc`.

```bash
#!/bin/bash

# Or wherever you stored yours
config=/home/ben/hypha/vpn/utilities.hypha.coop-UDP4-13313-ovpn-ben-config.ovpn

hyphaup(){
  echo 'Username is ovpn_ben & password is in passbolt'
  openvpn3 session-start --config "${config}"
}

hyphadown(){
  openvpn3 session-manage --disconnect --config "${config}"
}
```

You can also check if a session is active via `openvpn3 sessions-list`.

**Comment by uditvira** [comment]
@ASoTNetworks can you look into these issues?

**Comment by ASoTNetworks** [comment]
I figured out the issue with the VPN is that pfSense export the config with OpenVPN 2.5 support by default and there is an option to disable that which allows OpenVPN 2.4 to work.

The DNS should be set to the VPN's pushed config which should be `198.51.100.1` and `2001:470:b1f3:2::1`
