### ISSUE TITLE
Set up big dipper for the public testnet

### ISSUE THREAD

**Issue by uditvira** [hyphacoop/cosmos-organizing#26]
Follow instructions here: http://docs.bigdipper.live/cosmos-based/frontend/setup after setting up BDJuno (instructions in the same resource)

we might have to use the tharsis fork, but can confirm later

**Comment by uditvira** [comment]
- [ ] el find time with udit next thursday

**Comment by dcwalk** [comment]
tested yesterday, udit doing some more testing today. we aren't sure if this is now bully @uditvira 's task

**Comment by uditvira** [comment]
we did this using the old big dipper. this version might not work for the new upgrade. closing for now. we can just monitor our current explorer and see how it responds to the upgrade.
