### ISSUE TITLE
Set up panic for cosmos nodes

### ISSUE THREAD

**Issue by uditvira** [hyphacoop/cosmos-organizing#32]
See here https://github.com/SimplyVC/panic_cosmos/blob/master/doc/INSTALL_AND_RUN.md

should configure running for all vega testnet nodes we are responsible for

**Comment by uditvira** [comment]
to enable telegram, can refer to these links:
- https://www.siteguarding.com/en/how-to-get-telegram-bot-api-token
- also maybe this https://sean-bradley.medium.com/get-telegram-chat-id-80b575520659

**Comment by ASoTNetworks** [comment]
I have set up PANIC-Cosmos on a VM at panic1.cosmos.hypha.coop which monitors nodes over RPC and sends alerts to our Telegram channel.

**Comment by uditvira** [comment]
done
