### ISSUE TITLE
Setting up the testnet playbook using this document as a starting point https://hackmd.io/ak4LzC-JSNSukbtVF0jbjg?view

### ISSUE THREAD

**Issue by uditvira** [hyphacoop/cosmos-organizing#35]

**Comment by uditvira** [comment]
lauren + yaru are using this document and refining it as they set up their own tesnet nodes

**Comment by dcwalk** [comment]
no action from others on hypha team @RangerMauve will check this out this week

**Comment by RangerMauve** [comment]
I used this to set up a testnet node, it was very useful. 🎉

**Comment by uditvira** [comment]
udit did a big clean up of this last week and added the state sync section also
