### ISSUE TITLE
Onboard Mai to Cosmos project

### ISSUE THREAD

**Issue by uditvira** [hyphacoop/cosmos-organizing#38]
### Hypha onboarding 
- [x] share handbook.hypha.coop particularly the [onboarding checklist](https://handbook.hypha.coop/onboarding.html#onboarding-checklist) (edit: a member has to do most of those actions on the list! not the person being onboarded)

### Communications
- [x] add to shared ig slack
- [x] add to developer discord
- [x] add to cosmos hub private discord
- [x] add to matrix

### Project management
- [x] share ig-hypha meeting check-in doc (maybe it's an open doc?)
- [x] add as collaborator to cosmos-organizing project board
- [x] invite to weekly internal meeting
- [x] invite to weekly ig-hypha meeting

## Project materials

Feel free to to browse through most of these. The one's labelled with a "⭐" are likely more relevant.

### Cosmos Context
- [ ] [Cosmos Whitepaper](https://cosmos.network/cosmos-whitepaper.pdf) 
- [x] [https://cosmos.network/intro](https://cosmos.network/intro) ⭐
- [ ] [Zaki's vision for Cosmos Hub future](https://github.com/cosmosdevs/atom2021)
- [ ] [Jae's vision for Cosmos Hub future](https://github.com/jaekwon/cosmos_roadmap/tree/master/shape_of_cosmos)
- [x] [Gaia is a Port City](https://blog.cosmos.network/the-cosmos-hub-is-a-port-city-5b7f2d28debf) ⭐
- [ ] [IBC overview paper](https://github.com/cosmos/ics/blob/master/papers/2020-05/build/paper.pdf) 
- [ ] [Cosmos 2020 a look back](https://blog.cosmos.network/cosmos-2020-a-look-back-a5ee7e37388d)
- [ ] [How Seven Teams Collaborated To Deliver The Biggest Software Upgrade In The Cosmos Universe](https://blog.cosmos.network/how-seven-teams-collaborated-to-deliver-the-biggest-software-upgrade-in-the-cosmos-universe-2288f4f9afe8)

### Cosmos tools
Get a sense of all these tools that are core to the ecosystem

- [x] [keplr wallet](https://www.keplr.app/)
- [ ] explorers (big dipper, mintscan)
- [x] [Cosmos forum](https://forum.cosmos.network/)

### Cosmos ecosystem
Start getting familiar with other chains/projects in the ecosystem. Starting with:
- [ ] Osmosis
- [ ] Regen

### Hypha Project Context ⭐
- [ ] [State of Governance](https://hub.cosmos.network/main/governance/state_of_cosmos_governance_2021.html)
- [x] [Overview of on-chain governance](https://hub.cosmos.network/main/governance/overview.html)
- [ ] [Testnet Action Plan](https://docs.google.com/document/d/1ZlSP_3slDDXyG3Ig5VTUB0gyFoqQaGbEbqANU0Wehd4/edit#heading=h.ckngdg9s4zqw)
- [ ] [vega-testnet repository](https://github.com/cosmos/vega-test/)
- [x] [our upcoming forum proposal](https://docs.google.com/document/d/1RIoGDKRpDBtKZYonRHuIADfQ_FcuqKFASFIPKqIul2U/edit?usp=sharing)

### General blockchain / governance context
* :video_camera: Ethan Buchman, [Philosophical Perspective on the Engineering of Web3](https://www.youtube.com/watch?v=Luh7m7YHRts), 2019
* :newspaper: Vitalik Buterin, [Notes on Blockchain Governance](https://vitalik.ca/general/2017/12/17/voting.html), 2017 ⭐
* :newspaper: Vitalik Buterin, [Blockchain voting is overrated among uninformed people but underrated among informed people](https://vitalik.ca/general/2021/05/25/voting2.html), 2021
* :newspaper: Nathan Schneider, [Online Communities Are Still Catching Up to My Mother's Garden Club](https://hackernoon.com/online-communities-aint-got-nothing-on-my-mothers-garden-club-because-of-implicit-feudalism-gc2z34y4), 2021
* :newspaper: Vitalik Buterin, [DAOs, DACs, DAs and More: An Incomplete Terminology Guide](https://blog.ethereum.org/2014/05/06/daos-dacs-das-and-more-an-incomplete-terminology-guide/), 2014 
* :newspaper: Linda Xie, [A beginner's guide to DAOs](https://linda.mirror.xyz/Vh8K4leCGEO06_qSGx-vS5lvgUqhqkCz9ut81WwCP2o), 2021 ⭐
* :newspaper: Gregory Landua, [Community Stake Governance Model](https://medium.com/regen-network/community-stake-governance-model-b949bcb1eca3), 2019
* :newspaper: Pat Rawson, [Ownership in Cryptonetworks](https://blog.curvelabs.eu/ownership-in-cryptonetworks-96f13f4a113e), 2021
* :newspaper: Nadia Eghbal, [Governance without Foundations](https://nadiaeghbal.com/foundations), 2018
* :page_facing_up: Primavera De Filippi, Benjamin Loveluck, [The invisible politics of Bitcoin: governance crisis of a decentralised infrastructure](https://policyreview.info/articles/analysis/invisible-politics-bitcoin-governance-crisis-decentralised-infrastructure), Internet Policy Review, vol. 5, no. 3, 2016
* :speaker:  https://theblockchainsocialist.com/the-heterodox-politics-of-the-internet-of-blockchains-and-sustainability-existentialism/
* :page_facing_up: https://richdecibels.substack.com/p/9-decentralised-tech-and-the-future

**Comment by uditvira** [comment]
- added the forum proposal to the top comment @maisutton

**Comment by uditvira** [comment]
- [ ] add Mai to internal google drive

**Comment by dcwalk** [comment]
Some additional thoughts on governance and web3:
- Admins, mods, and benevolent dictators for life: The implicit feudalism of online communities https://mediarxiv.org/sf432/download?format=pdf
- Coops to crypto: https://untangled.substack.com/p/from-co-ops-to-crypto
- Quinn Dupont Experiments in algorithmic governance: A history and ethnography of “The DAO,” a failed decentralized autonomous organization [link :link: ](https://www.researchgate.net/profile/Quinn-Dupont/publication/319529311_Experiments_in_Algorithmic_Governance_A_history_and_ethnography_of_The_DAO_a_failed_Decentralized_Autonomous_Organization/links/59b15fc2a6fdcc3f888dfac8/Experiments-in-Algorithmic-Governance-A-history-and-ethnography-of-The-DAO-a-failed-Decentralized-Autonomous-Organization.pdf) 
- Blockchain as a confidence machine: The problem of trust & challenges of governance
PrimaveraDe Filippi Morshed Mannan Wessel Reijers  https://www.sciencedirect.com/science/article/pii/S0160791X20303067
- Primavera De Filippi Blockchain Technology and Decentralized Governance: The Pitfalls of a Trustless Dream  https://papers.ssrn.com/sol3/papers.cfm?abstract_id=3524352

Things that resonate as accurate but less exciting:
- The way that VC/silicon valley wants to be in the space: https://a16z.com/2019/11/12/the-end-of-centralization-and-the-future-of-trust/      https://a16z.com/wp-content/uploads/2021/10/How-to-Win-the-Future-1.pdf
- https://www.youtube.com/watch?v=lH1pEE0W3ug


We were shared this for relevance to community pool: 
- https://podcasts.apple.com/bg/podcast/3-defi-treasuries-with-hasu-monetsupply-and-larry-sukernik/id1587401478?i=1000542116428

**Comment by maisutton** [comment]
Additional context/readings

- [ ] VIDEO: Intro to the Cosmos Network - Sunny Aggarwal https://www.youtube.com/watch?v=XAetXKTikLM 
- [ ] VIDEO: Future of the Cosmos Hub https://www.youtube.com/watch?v=8bn22V2_8O4
- [ ] A Cosmos Thesis from Paradigm https://research.paradigm.xyz/cosmos-thesis
- [ ] Announcing Informal https://interchain-io.medium.com/past-present-future-icf-r-and-d-introducing-informal-systems-e50d14383f05
- [ ] ICF => IG https://interchain-io.medium.com/interchain-foundation-2020-7bcf9a9ccad5
- [ ] Interchain Core Entities https://interchain-io.medium.com/expansion-of-the-cosmos-ff2447c25e5
- [ ] Current List of Core Entities https://github.com/orgs/cosmos/teams
- [ ] Expanded Foundation Council https://interchain-io.medium.com/driving-decentralization-in-our-governance-254a63d4ba19

**Comment by dcwalk** [comment]
keep in progress as mai is using to track what resources they have looked at! Aiming to close next week
