### ISSUE TITLE
Onboard Mauve

### ISSUE THREAD

**Issue by uditvira** [hyphacoop/cosmos-organizing#41]
### Hypha onboarding 
- [x] share handbook.hypha.coop particularly the [onboarding checklist](https://handbook.hypha.coop/onboarding.html#onboarding-checklist) (edit: a member has to do most of those actions on the list! not the person being onboarded)
* #todo google: Mauve will send us their preffered google account (it's )
* RangerMauve
    * #todo udit add RangerMauve as collab on hypha specific cosmos repo (Mauve shared already)
    * #todo see if RangerMauve should be added to cosmos organization
    * #todo make mauve@hypha.coop
        * here our the guides https://handbook.hypha.coop/guides.html#email 

### Communications
- [x] add to shared ig slack #todo udit
- [x] add to developer discord https://discord.gg/cosmosnetwork 
- [x] add to cosmos hub private discord (Mauve shared their discord)
- [x] add to matrix 
    - [x] Hyphacoop:cosmos 
    - [x] Hyphacoop:cosmos-infra

- we want to respect work-life boundaries
    - more on Wed-Fri for Mauve

### Project management
- [x] share ig-hypha meeting check-in doc (maybe it's an open doc?)
- [x] add as collaborator to cosmos-organizing project board
- [x] invite to weekly internal meeting
    - 1:00pm fridays
- [ ] invite to weekly ig-hypha testnet meeting
    - 11:30am wednesdays

## Project materials

Feel free to to browse through most of these. The one's labelled with a "⭐" are likely more relevant.

### Cosmos Context

- [ ] sdk docs at docs.cosmos.network ⭐
- [ ] [Cosmos Whitepaper](https://cosmos.network/cosmos-whitepaper.pdf) ⭐
- [ ] [https://cosmos.network/intro](https://cosmos.network/intro) ⭐
- [ ] [Zaki's vision for Cosmos Hub future](https://github.com/cosmosdevs/atom2021)
- [ ] [Jae's vision for Cosmos Hub future](https://github.com/jaekwon/cosmos_roadmap/tree/master/shape_of_cosmos)
- [ ] [Gaia is a Port City](https://blog.cosmos.network/the-cosmos-hub-is-a-port-city-5b7f2d28debf) ⭐
- [ ] [IBC overview paper](https://github.com/cosmos/ics/blob/master/papers/2020-05/build/paper.pdf) 
- [ ] [Cosmos 2020 a look back](https://blog.cosmos.network/cosmos-2020-a-look-back-a5ee7e37388d)
- [ ] [How Seven Teams Collaborated To Deliver The Biggest Software Upgrade In The Cosmos Universe](https://blog.cosmos.network/how-seven-teams-collaborated-to-deliver-the-biggest-software-upgrade-in-the-cosmos-universe-2288f4f9afe8)

### Cosmos tools
Get a sense of all these tools that are core to the ecosystem

- [ ] [keplr wallet](https://www.keplr.app/)
- [ ] explorers (big dipper, mintscan)
- [ ] [Cosmos forum](https://forum.cosmos.network/)

### Cosmos ecosystem
Start getting familiar with other chains/projects in the ecosystem. Starting with:
- [ ] Osmosis
- [ ] Regen

### Hypha Project Context ⭐

- [ ] [State of Governance](https://hub.cosmos.network/main/governance/state_of_cosmos_governance_2021.html)
- [ ] [Overview of on-chain governance](https://hub.cosmos.network/main/governance/overview.html)
- [ ] [Testnet Action Plan]  ⭐ (https://docs.google.com/document/d/1ZlSP_3slDDXyG3Ig5VTUB0gyFoqQaGbEbqANU0Wehd4/edit#heading=h.ckngdg9s4zqw)
- [ ] [vega-testnet repository](https://github.com/cosmos/vega-test/)  ⭐ 
- [ ] [our upcoming forum proposal](https://docs.google.com/document/d/1RIoGDKRpDBtKZYonRHuIADfQ_FcuqKFASFIPKqIul2U/edit?usp=sharing)

**Comment by dcwalk** [comment]
Mauve thinks all resources here are good as non-urgent reference. also theythink they have all cal invites
