### ISSUE TITLE
Write up 2022 SLA for hypha <> icf

### ISSUE THREAD

**Issue by uditvira** [hyphacoop/cosmos-organizing#47]
@uditvira for Jan 3 2022

**Comment by uditvira** [comment]
* Udit to revise based on Maria's comments on expanding the governance section
* Share with Mai and Lexa

**Comment by uditvira** [comment]
* this is being reviewed by maria at icf

**Comment by uditvira** [comment]
some delays because of synchronization across teams. our budget has been approved

**Comment by LexaMichaelides** [comment]
Waiting on ICF, then will be done
