### ISSUE TITLE
Onboard Lexa

### ISSUE THREAD

**Issue by uditvira** [hyphacoop/cosmos-organizing#50]
- udit to chat on Jan 3rd

**Comment by LexaMichaelides** [comment]
Lifted from Mai's list:

### Hypha Project Context  ⭐
**Text-based, context/theory**
- [x] [State of Cosmos Governance 2021](https://hub.cosmos.network/main/governance/state_of_cosmos_governance_2021.html)
- [x] [Overview of Proposal Process & Governance Mechanism](https://hub.cosmos.network/main/governance/overview.html)
- [x] [our upcoming forum proposal](https://docs.google.com/document/d/1RIoGDKRpDBtKZYonRHuIADfQ_FcuqKFASFIPKqIul2U/edit?usp=sharing)


**Code or technical (needs more tech awareness before I can understand)** 
- [ ] [vega-testnet repo](https://github.com/cosmos/vega-test/)
- [ ] [Testnet Action Plan](https://docs.google.com/document/d/1ZlSP_3slDDXyG3Ig5VTUB0gyFoqQaGbEbqANU0Wehd4/edit?usp=sharing)

**Comment by uditvira** [comment]
https://spark-papyrus-5e0.notion.site/From-0-to-Cosmonaut-71fe11356e37448499b6f1ac28dc956b
