### ISSUE TITLE
Implement the testnet creator MVP in three phases

### ISSUE THREAD

**Issue by uditvira** [hyphacoop/cosmos-organizing#61]
1. get a gaia node running with ansible
  2. get a network of nodes running
  3. different roles for nodes (archive, sentry, validator etc.)

**Comment by RangerMauve** [comment]
Progress on the gaiad role:

- Have general code for setting up gaiad repo and compiling
- Code for copying config files
- Ansible variables with default values for role

TODO:
- Copying ansible variables into config files using python script
- Firewall rules for role
- Running on a VM

**Comment by uditvira** [comment]
Now:
* gaia can be set up as it's own systemd service
* from today cosmovisor will also work
* some config var injection is working
* arbitrary address books and genesis file locations
* moniker is pulled from host name

What we don't have
* fetch host names and inject them
* what about node ids?

New:
* add new ansible that pulls gaiad binary and adds to update path
