### ISSUE TITLE
Post-proposal work

### ISSUE THREAD

**Issue by LexaMichaelides** [hyphacoop/cosmos-organizing#72]
This tracking issue is for subtasks we intend to tackle once our CSP has passed on-chain. 

## External platform coordination
- [ ] Discord (Daniela): Set up a read-only governance channel for proposal updates on the forum (not on-chain)
- [ ] Telegram (Gavin?): Switch to an announcement-only channel (tentative) 
- [ ] Produce clearer structures/guidelines for how to use @ CosmosGov (e.g. Moving Summary templates)

## Forum changes
- [x] Aesthetic revamp
- [x] Architectural changes to categories
- [ ] Investigate roles/groups
- [ ] Linking category top-level description posts to educational content posts (e.g. Param Change description post should be like a how-to for making that kind of proposal and should be linked in the Best Practices post)

## Content creation
- [ ] Best practices for making a proposal (idea post, draft, solicit feedback, changelog, promotion, pinning to IPFS)
- [ ] Better category descriptions for top-level categories
- [ ] Better category descriptions for Hub Proposal subcategories
- [ ] Templates for proposal types (incl 'delete me' notes for OP)

**Comment by uditvira** [comment]
This was broken up into:
- #86 
- #87 
- #88 
- #89 
- #90
- #91 
- #92 
closing
