### ISSUE TITLE
Investigate gRPC endpoint not running on theta testnet

### ISSUE THREAD

**Issue by uditvira** [hyphacoop/cosmos-organizing#75]

**Comment by ASoTNetworks** [comment]
The issue was we tunnelled through nginx reverse proxy for SSL but we use `proxy_pass` instead of `grpc_pass`.

Changing to `grpc_pass` solved the issue.
```
	location / {
		grpc_pass          grpc://127.0.0.1:9090;
		proxy_redirect     off;
	}
```

**Comment by uditvira** [comment]
Nice catch @ASoTNetworks! Added an issue to the ansible repo also so we don't forget to fix there
