### ISSUE TITLE
Write moving summary for BlocksUnited prop

### ISSUE THREAD

**Issue by uditvira** [hyphacoop/cosmos-organizing#81]

**Comment by LexaMichaelides** [comment]
Udit to write the summary
Mai to review and tweet @ CosmosGov

**Comment by uditvira** [comment]
Added here https://docs.google.com/document/d/1djGNT_D9uLVHn1Y0hRuTZZaCBrSasODm_KVOSd6urC0/edit?usp=sharing

**Comment by uditvira** [comment]
tweeted
