### ISSUE TITLE
Produce brand guidelines for governance work

### ISSUE THREAD

**Issue by uditvira** [hyphacoop/cosmos-organizing#95]
- [x] Create Arena channel 
- [ ] Pick colour scheme (Cosmos and governance concepts)
- [ ] Produce logo/image for @ CosmosGov
- [ ] Change forum colours to match

**Comment by LexaMichaelides** [comment]
Thought dump
- not the Cosmos logo
- maybe something reminiscent of the EU, like a flag?
- not super focused on Hypha, but could be 'Hypha in vibe'

Blue background with white or yellow ATOM logo?

**Comment by LexaMichaelides** [comment]
Think of this as an opportunity to rebrand, not just changing it for the sake of changing it. Establish a tone - maybe matching colour scheme with forum and Twitch stream?

**Comment by maisutton** [comment]
Cosmos brand Are.na board from Sam: https://www.are.na/share/ttajjNH

**Comment by maisutton** [comment]
Udit and Mai met with Hank to discuss brand -- he will get back to us by beginning May and let us know his timeline and availability.

**Comment by uditvira** [comment]
I'm currently reviewing the SOW from Hank. Will finalized by next week

**Comment by uditvira** [comment]
closing in favour #137
