### ISSUE TITLE
Establish public facing mnemonic rule and associated private keys

### ISSUE THREAD

**Issue by uditvira** [hyphacoop/cosmos-organizing#96]

**Comment by ASoTNetworks** [comment]
Must be easily distinguishable such as repeated words or phases and the mnemonic can be restored.

Use https://build-bip39.groestlcoin.org/bip39/ to make definable keys.

Examples:
`abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon art`


`abandon cabbage abandon cabbage abandon cabbage abandon cabbage abandon cabbage abandon cabbage abandon cabbage abandon cabbage abandon cabbage abandon cabbage abandon cabbage abandon garage`

**Comment by dasanchez** [comment]
Add to cosmos-configurations-private as a separate page
